# Simple package

name: strathsupport-package 
parent: default

matches:
  - trigger: ":reinstall"
    replace: "espanso uninstall strathsupport-package\nespanso package install strathsupport-package https://github.com/mhughes2k/strathsupport-package --external\nespanso restart\n"
  - trigger: ":regards"
    replace: "Regards\n\nMichael Hughes\nMyplace Support"
  - trigger: ":close"
    replace: "As we have no further response with regards to this query, we are going to close this call."
  - trigger: ":reopen"
    replace: "Should there be any further information please do get in contact again with the Helpdesk (help@strath.ac.uk) who can re-open it."
  - trigger: ":helproles"
    replace: "https://support.myplace.strath.ac.uk/display/MS/Roles"
  - trigger: ":email-close"
    replace: "{{close}}\n\n{{reopen}}\n\n{{regards}}"
    vars:
      - name: close
        type: match
        params:
          trigger: ":close"
      - name: reopen
        type: match
        type: match
        params:
          trigger: ":reopen"
      - name: regards
        type: match
        params:
          trigger: ":regards"
  - trigger: ":noteams"
    replace: "The University has not yet deployed MS teams, so it is not possible to generally join.\nHowever, if the West Partnership were to add this email address as a “guest user”, it should be possible to log in and access these resources." 
  - trigger: ":rollovermove"
    replace: "This site is marked with a rollover action of "move", meaning that it always will live on the latest academic year instance of Myplace (https://support.myplace.strath.ac.uk/display/MS/Rollover+Explained).\n\nThis means that the site wouldn't be available until the end of 19th June."